### ISSUE TITLE
Errors and questions

### ISSUE THREAD

**Issue by Random-Walker-a** [AI4Risk/GraphGenerator#1]
Here are few questions:
1. the code snippet for CPGAN is quite irrelevant of the original paper, since there's no GAN architecture at all, only a simple GAE structure.
2. Graphrnn is a model designed for a fundamental different tasks with multiple graphs as training set. Since this repo is for large graph simulation, why not include models like NetGAN and CELL?
3. Are you the authors of BTGAE, to my knowledge, there's no publicly available script for the work. Can you please provide the link(e.g. arxiv) of the work to avoid confusion.
I hope the authors of this repo will help resolve these issues to avoid further confusion.

**Comment by ZZiCai** [comment]
1. Regarding the first question: The authors of CPGAN lost the original source code due to a system reinstallation, and only the GAE version was re-implemented. Therefore, I have also noted in the readme that it is the GAE version of CPGAN.
2. In response to the second question: This repository is continuously being updated, and more baselines for large graph simulation will be added in the future, including NetGAN and CELL, among others.
3. For the third question: The BTGAE is currently under submission. We have not posted the paper on arXiv yet, so we are unable to provide a link to the preprint.
